apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: katka-node-azure 
  janus-idp.io/tekton: katka-node-azure
  backstage.io/kubernetes-id: katka-node-azure
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: katka-node-azure
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml