apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: katka-node-azure-gitops
  description: This is GitOps manifest for katka-node-azure   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=katka-node-azure
    backstage.io/kubernetes-id: katka-node-azure 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: katka-rhtap/katka-node-azure-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: katka-rhtap.katka-node-azure-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:katka-node-azure
